# Generated by Django 4.2.1 on 2023-05-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sonet", "0004_hashtag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="post",
            name="hashtags",
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="media",
            field=models.FileField(blank=True, null=True, upload_to="media/"),
        ),
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(related_name="posts", to="sonet.hashtag"),
        ),
    ]
