# Generated by Django 4.2.1 on 2023-05-28 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sonet", "0007_remove_post_hashtags_post_hashtags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="hashtags",
            new_name="hashtag",
        ),
    ]
