# Generated by Django 4.2.1 on 2023-05-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sonet", "0009_alter_hashtag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hashtag",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
