# Generated by Django 4.2.1 on 2023-05-29 06:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sonet", "0010_alter_hashtag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
