# Generated by Django 4.2.1 on 2023-05-31 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sonet", "0012_post_likes_alter_hashtag_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
        migrations.AddField(
            model_name="post",
            name="comment",
            field=models.ManyToManyField(
                blank=True,
                related_name="post_comments",
                through="sonet.Comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="sonet.post",
            ),
        ),
    ]
