# Generated by Django 4.2.1 on 2023-06-02 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("sonet", "0013_remove_post_comments_post_comment_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="comment",
            field=models.ManyToManyField(
                blank=True,
                related_name="commented_posts",
                through="sonet.Comment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
