# Generated by Django 4.2.1 on 2023-05-31 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_user_bio_user_profile_picture_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="follower",
            name="user",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
