# Generated by Django 4.2.1 on 2023-05-31 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_follower_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follower",
            name="follower",
        ),
        migrations.AlterField(
            model_name="follower",
            name="following",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
