# Generated by Django 4.2.1 on 2023-05-31 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0009_remove_follower_following_follower_following"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follower",
            name="following",
        ),
        migrations.AddField(
            model_name="follower",
            name="following",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="follower",
            ),
        ),
    ]
