# Generated by Django 4.2.1 on 2023-06-02 07:41

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0011_alter_follower_following"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="followers",
            field=models.ManyToManyField(
                blank=True, related_name="following_set", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="follower",
            name="following",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_following",
                to=settings.AUTH_USER_MODEL,
                verbose_name="follower",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="following",
            field=models.ManyToManyField(
                blank=True, related_name="followers_set", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
